receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4319
      http:
        endpoint: localhost:4320

exporters:
  jaeger_storage_exporter:
    trace_storage: memstore 

extensions:
  jaeger_storage:
    backends:
      memstore:
        memory:
          max_traces: 100000
  jaeger_query:
    storage:
      traces: memstore

service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger_storage_exporter]